version: "3.7"
services:

  redis1:
    container_name: redis1
    image: redis:6.2.5-alpine
    ports:
      - target: 6379
        published: 6379

  redis2:
    container_name: redis2
    image: redis:6.2.5-alpine
    ports:
      - target: 6379
        published: 7379

  redis3:
    container_name: redis3
    image: redis:6.2.5-alpine
    ports:
      - target: 6379
        published: 8379

  sentinel1:
    container_name: sentinel1
    build:
      context: devops
      dockerfile: sentinel.Dockerfile
    ports:
      - target: 26379
        published: 26379

  sentinel2:
    container_name: sentinel2
    build:
      context: devops
      dockerfile: sentinel.Dockerfile
    ports:
      - target: 26379
        published: 36379

  sentinel3:
    container_name: sentinel3
    build:
      context: devops
      dockerfile: sentinel.Dockerfile
    ports:
      - target: 26379
        published: 46379
